#pragma once
#include "global.h"

#define TT_0 AT(u8"关于###TT_0",u8"About###TT_0")
#define TT_1 AT(u8"这是关于",u8"About the project")
#define TT_2 AT(u8"这是中文的关于。",u8"This is about English.")
#define TT_3 AT(u8"https://github.com/log159/ShinobuDiary",u8"https://github.com/log159/ShinobuDiary")
#define TT_4 AT(u8"语言选择",u8"Language Select")
#define TT_5 AT(u8"语言配置###TT_5",u8"Language Setting###TT_5")
#define TT_6 AT(u8"LLM 选择",u8"LLM Select")
#define TT_7 AT(u8"LLM 配置###TT_7",u8"LLM Setting###TT_7")
#define TT_8 AT(u8"保存配置",u8"Save Setting")
#define TT_9 AT(u8"TTS 选择",u8"TTS Select")
#define TT_10 AT(u8"TTS 配置###TT_10",u8"TTS Setting###TT_10")
#define TT_11 AT(u8"STT 选择",u8"STT Select")
#define TT_12 AT(u8"STT 配置###TT_12",u8"STT Setting###TT_12")
#define TT_13 AT(u8"MT 选择",u8"MT Select")
#define TT_14 AT(u8"MT 配置###TT_14",u8"MT Setting###TT_14")
#define TT_15 AT(u8"帮助###TT_15",u8"Help###TT_15")
#define TT_16 AT(u8"项目的帮助",u8"Help about the project.")
#define TT_17 AT(u8"这是中文帮助",u8"This is English help.")
#define TT_18 AT(u8"ChatGPT",u8"ChatGPT")
#define TT_19 AT(u8"讯飞星火",u8"SparkDesk")
#define TT_20 AT(u8"深度求索",u8"DeepSeek")
#define TT_21 AT(u8"vits-simple-api",u8"vits-simple-api")
#define TT_22 AT(u8"GPT-SoVits",u8"GPT-SoVits")
#define TT_23 AT(u8"用户自定义的-Vits",u8"MySelf-Vits")
#define TT_24 AT(u8"百度智能云",u8"BaiDuZhiNengYun")
#define TT_25 AT(u8"百度翻译",u8"BaiDufanYi")
#define TT_26 AT(u8"讲述人编号",u8"speaker Id")
#define TT_27 AT(u8"模型选择",u8"model select")
#define TT_28 AT(u8"情感参数(适用于w2v2)",u8"emotional id (for w2v2)")
#define TT_29 AT(u8"目标语言(适用于api2)",u8"target language (for api2)")
#define TT_30 AT(u8"https://github.com/jianchang512/gptsovits-api",u8"https://github.com/jianchang512/gptsovits-api")
#define TT_31 AT(u8"自定义的请求",u8"custom url")
#define TT_32 AT(u8"用户配置###TT_32",u8"User Setting###TT_32")
#define TT_33 AT(u8"用户配置%d",u8"User Setting%d")
#define TT_34 AT(u8"删除这个用户配置？",u8"Delete this user configuration?")
#define TT_35 AT(u8"删除？",u8"Delete?")
#define TT_36 AT(u8"是",u8"YES")
#define TT_37 AT(u8"否",u8"NO")
#define TT_38 AT(u8"小忍日记 %c %s###ShinobuDiaryMain",u8"ShinobuDiary %c %s###ShinobuDiaryMain")
#define TT_39 AT(u8"样式面板###ShinobuDiaryStyle",u8"Style Editor###ShinobuDiaryStyle")
#define TT_40 AT(u8"样式配置",u8"Style Setting")
#define TT_41 AT(u8"样式面板",u8"Style Editor")
#define TT_42 AT(u8"应用程序平均 % .3f毫秒 / 实际帧率(% .1f FPS)","Application average %.3f ms/frame (%.1f FPS)")
#define TT_43 AT(u8"颜色选择器##Selector", u8"Colors##Selector")
#define TT_44 AT(u8"字体选择器##Selector", u8"Fonts##Selector")
#define TT_45 AT(u8"框架圆角", u8"FrameRounding")
#define TT_46 AT(u8"窗口边框", u8"WindowBorder")
#define TT_47 AT(u8"框架边框", u8"FrameBorder")
#define TT_48 AT(u8"弹窗边框", u8"PopupBorder")
#define TT_49 AT(u8"保存样式", u8"Save Style")
#define TT_50 AT(u8"恢复默认", u8"Revert Origin")
#define TT_51 AT(u8"尺寸", u8"Sizes")
#define TT_52 AT(u8"主要", u8"Main")
#define TT_53 AT(u8"窗口内边距", u8"WindowPadding")
#define TT_54 AT(u8"框架内边距", u8"FramePadding")
#define TT_55 AT(u8"元素间距", u8"ItemSpacing")
#define TT_56 AT(u8"元素内间距", u8"ItemInnerSpacing")
#define TT_57 AT(u8"触控额外内边距", u8"TouchExtraPadding")
#define TT_58 AT(u8"缩进间距", u8"IndentSpacing")
#define TT_59 AT(u8"滚动条大小", u8"ScrollbarSize")
#define TT_60 AT(u8"抓取条大小", u8"GrabMinSize")
#define TT_61 AT(u8"边框", u8"Borders")
#define TT_62 AT(u8"窗口边框大小", u8"WindowBorderSize")
#define TT_63 AT(u8"子窗口边框大小", u8"ChildBorderSize")
#define TT_64 AT(u8"弹窗边框大小", u8"PopupBorderSize")
#define TT_65 AT(u8"框架边框大小", u8"FrameBorderSize")
#define TT_66 AT(u8"标签边框大小", u8"TabBorderSize")
#define TT_67 AT(u8"标签栏边框大小", u8"TabBarBorderSize")
#define TT_68 AT(u8"标签栏上划线大小", u8"TabBarOverlineSize")
#define TT_69 AT(u8"深色\0浅色\0经典\0", u8"Dark\0Light\0Classic\0")
#define TT_70 AT(u8"圆角", u8"Rounding")
#define TT_71 AT(u8"窗口圆角", u8"WindowRounding")
#define TT_72 AT(u8"子窗口圆角", u8"ChildRounding")
#define TT_73 AT(u8"框架圆角", u8"FrameRounding")
#define TT_74 AT(u8"弹窗圆角", u8"PopupRounding")
#define TT_75 AT(u8"滚动条圆角", u8"ScrollbarRounding")
#define TT_76 AT(u8"抓取条圆角", u8"GrabRounding")
#define TT_77 AT(u8"标签圆角", u8"TabRounding")
#define TT_78 AT(u8"表格", u8"Tables")
#define TT_79 AT(u8"单元格内边距", u8"CellPadding")
#define TT_80 AT(u8"表格倾斜标题角度", u8"TableAngledHeadersAngle")
#define TT_81 AT(u8"表格倾斜标题文本对齐", u8"TableAngledHeadersTextAlign")
#define TT_82 AT(u8"窗口", u8"Widgets")
#define TT_83 AT(u8"窗口标题对齐", u8"WindowTitleAlign")
#define TT_84 AT(u8"窗口菜单按钮位置", u8"WindowMenuButtonPosition")
#define TT_85 AT(u8"无\0左\0右\0", u8"None\0Left\0Right\0")
#define TT_86 AT(u8"按钮文本对齐", u8"ButtonTextAlign")
#define TT_87 AT(u8"当按钮大于其文本内容时应用对齐。", u8"Alignment applies when a button is larger than its text content.")
#define TT_88 AT(u8"可选择文本对齐", u8"SelectableTextAlign")
#define TT_89 AT(u8"当可选择项大于其文本内容时应用对齐。", u8"Alignment applies when a selectable is larger than its text content.")
#define TT_90 AT(u8"分隔符文本边框大小", u8"SeparatorTextBorderSize")
#define TT_91 AT(u8"分隔符文本对齐", u8"SeparatorTextAlign")
#define TT_92 AT(u8"分隔符文本内边距", u8"SeparatorTextPadding")
#define TT_93 AT(u8"对数滑块死区", u8"LogSliderDeadzone")
#define TT_94 AT(u8"停靠", u8"Docking")
#define TT_95 AT(u8"停靠分隔器大小", u8"DockingSplitterSize")
#define TT_96 AT(u8"工具提示", u8"Tooltips")
#define TT_97 AT(u8"鼠标悬停工具提示标志", u8"HoverFlagsForTooltipMouse")
#define TT_98 AT(u8"导航悬停工具提示标志", u8"HoverFlagsForTooltipNav")
#define TT_99 AT(u8"悬停标志_无延迟", u8"HoveredFlags_DelayNone")
#define TT_100 AT(u8"悬停标志_短延迟", u8"HoveredFlags_DelayShort")
#define TT_101 AT(u8"悬停标志_正常延迟", u8"HoveredFlags_DelayNormal")
#define TT_102 AT(u8"悬停标志_静止", u8"HoveredFlags_Stationary")
#define TT_103 AT(u8"悬停标志_无共享延迟", u8"HoveredFlags_NoSharedDelay")
#define TT_104 AT(u8"杂项", u8"Misc")
#define TT_105 AT(u8"显示窗口内边距", u8"DisplayWindowPadding")
#define TT_106 AT(u8"显示安全区域内边距", u8"DisplaySafeAreaPadding")
#define TT_107 AT(u8"颜色", u8"Colors")
#define TT_108 AT(u8"导出", u8"Export")
#define TT_109 AT(u8"到剪贴板\0到终端设备\0", u8"To Clipboard\0To TTY\0")
#define TT_110 AT(u8"仅修改颜色", u8"Only Modified Colors")
#define TT_111 AT(u8"筛选颜色", u8"Filter colors")
#define TT_112 AT(u8"不透明", u8"Opaque")
#define TT_113 AT(u8"透明度", u8"Alpha")
#define TT_114 AT(u8"混合的", u8"Both")
#define TT_115 AT(u8"在颜色列表中：\n左键单击颜色方块以打开颜色选择器，\n右键单击打开编辑选项菜单。", u8"In the color list:\nLeft-click on color square to open color picker,\nRight-click to open edit options menu.")
#define TT_116 AT(u8"闪烁指定颜色以标识其使用位置。", u8"Flash given color to identify places where it is used.")
#define TT_117 AT(u8"保存", u8"Save")
#define TT_118 AT(u8"恢复", u8"Revert")
#define TT_119 AT(u8"字体", u8"Fonts")
#define TT_120 AT(u8"窗口缩放", u8"Window scale")
#define TT_121 AT(u8"全局缩放", u8"Global scale")
#define TT_122 AT(u8"渲染", u8"Rendering")
#define TT_123 AT(u8"抗锯齿线", u8"Anti-aliased lines")
#define TT_124 AT(u8"抗锯齿线使用纹理", u8"Anti-aliased lines use texture")
#define TT_125 AT(u8"抗锯齿填充", u8"Anti-aliased fill")
#define TT_126 AT(u8"曲线细分容差", u8"Curve Tessellation Tolerance")
#define TT_127 AT(u8"圆形细分最大误差", u8"Circle Tessellation Max Error")
#define TT_128 AT(u8"%.0f 度", u8"%.0f deg")
#define TT_129 AT(u8"全局透明度", u8"Global Alpha")
#define TT_130 AT(u8"禁用透明度", u8"Disabled Alpha")
#define TT_131 AT(u8"为禁用项添加的额外透明度乘数(在当前 Alpha 值基础上叠加)。", u8"Additional alpha multiplier for disabled items (multiply over current value of Alpha).")
#define TT_132 AT(u8"颜色按钮位置",u8"ColorButtonPosition")
#define TT_133 AT(u8"左\0右\0", "Left\0Right\0")
#define TT_134 AT(u8"应用于常规窗口:当移动到屏幕边缘附近时，我们强制保持可见的量。",u8"Apply to regular windows: amount which we enforce to keep visible when moving near edges of your screen.")
#define TT_135 AT(u8"适用于每个窗口，菜单，弹出窗口，工具提示:我们避免显示内容的数量。如果看不到屏幕边缘，请进行调整(例如，在未配置缩放的TV)。","Apply to every windows, menus, popups, tooltips: amount where we avoid displaying contents. Adjust if you cannot see the edges of your screen (e.g. on a TV where scaling has not been configured).")
#define TT_136 AT(u8"文本", u8"Text")
#define TT_137 AT(u8"问号提示文本", u8"TextDisabled")
#define TT_138 AT(u8"窗口背景(无效的alpha)", u8"WindowBg(Invalid alpha.)")
#define TT_139 AT(u8"子窗口背景", u8"ChildBg")
#define TT_140 AT(u8"弹窗背景", u8"PopupBg")
#define TT_141 AT(u8"边框", u8"Border")
#define TT_142 AT(u8"边框阴影", u8"BorderShadow")
#define TT_143 AT(u8"框架背景", u8"FrameBg")
#define TT_144 AT(u8"框架背景悬停", u8"FrameBgHovered")
#define TT_145 AT(u8"框架背景激活", u8"FrameBgActive")
#define TT_146 AT(u8"标题背景", u8"TitleBg")
#define TT_147 AT(u8"标题背景激活", u8"TitleBgActive")
#define TT_148 AT(u8"标题背景折叠", u8"TitleBgCollapsed")
#define TT_149 AT(u8"菜单栏背景", u8"MenuBarBg")
#define TT_150 AT(u8"滚动条背景", u8"ScrollbarBg")
#define TT_151 AT(u8"滚动条抓取", u8"ScrollbarGrab")
#define TT_152 AT(u8"滚动条抓取悬停", u8"ScrollbarGrabHovered")
#define TT_153 AT(u8"滚动条抓取激活", u8"ScrollbarGrabActive")
#define TT_154 AT(u8"勾选标记", u8"CheckMark")
#define TT_155 AT(u8"滑块抓取", u8"SliderGrab")
#define TT_156 AT(u8"滑块抓取激活", u8"SliderGrabActive")
#define TT_157 AT(u8"按钮", u8"Button")
#define TT_158 AT(u8"按钮悬停", u8"ButtonHovered")
#define TT_159 AT(u8"按钮激活", u8"ButtonActive")
#define TT_160 AT(u8"标题", u8"Header")
#define TT_161 AT(u8"标题悬停", u8"HeaderHovered")
#define TT_162 AT(u8"标题激活", u8"HeaderActive")
#define TT_163 AT(u8"分隔符", u8"Separator")
#define TT_164 AT(u8"分隔符悬停", u8"SeparatorHovered")
#define TT_165 AT(u8"分隔符激活", u8"SeparatorActive")
#define TT_166 AT(u8"调整大小抓取", u8"ResizeGrip")
#define TT_167 AT(u8"调整大小抓取悬停", u8"ResizeGripHovered")
#define TT_168 AT(u8"调整大小抓取激活", u8"ResizeGripActive")
#define TT_169 AT(u8"标签悬停", u8"TabHovered")
#define TT_170 AT(u8"标签", u8"Tab")
#define TT_171 AT(u8"选中的标签", u8"TabSelected")
#define TT_172 AT(u8"选中的标签上划线", u8"TabSelectedOverline")
#define TT_173 AT(u8"标签变暗", u8"TabDimmed")
#define TT_174 AT(u8"选中的标签变暗", u8"TabDimmedSelected")
#define TT_175 AT(u8"选中的标签变暗上划线", u8"TabDimmedSelectedOverline")
#define TT_176 AT(u8"停靠预览", u8"DockingPreview")
#define TT_177 AT(u8"停靠空背景", u8"DockingEmptyBg")
#define TT_178 AT(u8"绘图线", u8"PlotLines")
#define TT_179 AT(u8"绘图线悬停", u8"PlotLinesHovered")
#define TT_180 AT(u8"绘图直方图", u8"PlotHistogram")
#define TT_181 AT(u8"绘图直方图悬停", u8"PlotHistogramHovered")
#define TT_182 AT(u8"表头背景", u8"TableHeaderBg")
#define TT_183 AT(u8"表格强边框", u8"TableBorderStrong")
#define TT_184 AT(u8"表格弱边框", u8"TableBorderLight")
#define TT_185 AT(u8"表格行背景", u8"TableRowBg")
#define TT_186 AT(u8"表格行背景交替", u8"TableRowBgAlt")
#define TT_187 AT(u8"文本链接", u8"TextLink")
#define TT_188 AT(u8"选中文本背景", u8"TextSelectedBg")
#define TT_189 AT(u8"拖放目标", u8"DragDropTarget")
#define TT_190 AT(u8"导航光标", u8"NavCursor")
#define TT_191 AT(u8"导航窗口高亮", u8"NavWindowingHighlight")
#define TT_192 AT(u8"导航窗口背景变暗", u8"NavWindowingDimBg")
#define TT_193 AT(u8"模态窗口背景变暗", u8"ModalWindowDimBg")
#define TT_194 AT(u8"未知的",u8"Unknown")
#define TT_195 AT(u8"当禁用抗锯齿线条时，您可能还想禁用样式中的边框。", u8"When disabling anti - aliasing lines, you'll probably want to disable borders in your style as well.")
#define TT_196 AT(u8"更快的线条使用纹理数据。要求后端使用双线性过滤进行渲染(不是点/最近过滤)。",u8"Faster lines using texture data. Require backend to render with bilinear filtering (not point/nearest filtering).")
#define TT_197 AT(u8"(R =半径，N =分段的大概数量)",u8"(R = radius, N = approx number of segments)")
#define TT_198 AT(u8"字体: \"%s\"\n%.2f 像素, %d 字形, %d 个文件(s)",u8"Font: \"%s\"\n%.2f px, %d glyphs, %d file(s)")
#define TT_199 AT(u8"设为默认值",u8"Set as default")
#define TT_200 AT(u8"那只敏捷的棕色狐狸跳过了那只懒狗",u8"The quick brown fox jumps over the lazy dog")
#define TT_201 AT(u8"字体比例",u8"Font scale")
#define TT_202 AT(u8"上升:%f，下降:%f，高度:%f",u8"Ascent: %f, Descent: %f, Height: %f")
#define TT_203 AT(u8"回退字符: '%s' (U+%04X)",u8"Fallback character: '%s' (U+%04X)")
#define TT_204 AT(u8"省略号字符: '%s' (U+%04X)",u8"Ellipsis character: '%s' (U+%04X)")
#define TT_205 AT(u8"纹理区域:关于 %d 像素 ~%dx%d 像素",u8"Texture Area: about %d px ~%dx%d px")
#define TT_206 AT(u8"输入%d: \'%s\'，过采样:(%d，%d)，像素快照: %d，偏移量:(%.1f，%.1f)",u8"Input %d: \'%s\', Oversample: (%d,%d), PixelSnapH: %d, Offset: (%.1f,%.1f)")
#define TT_207 AT(u8"字形",u8"Glyphs")
#define TT_208 AT(u8"字形 (%d)",u8"Glyphs (%d)")
#define TT_209 AT(u8"字形",u8"glyphs")
#define TT_210 AT(u8"字形",u8"glyph")
#define TT_211 AT(u8"字体图集",u8"Font Atlas")
#define TT_212 AT(u8"字体图集 (%dx%d 像素)",u8"Font Atlas (%dx%d pixels)")
#define TT_213 AT(u8"应用文字颜色渲染",u8"Tint with Text Color")
#define TT_214 AT(u8"复制为..",u8"Copy as..")
#define TT_215 AT(u8"当前的",u8"Current")
#define TT_216 AT(u8"原来的",u8"Original")
#define TT_217 AT(u8"字符码点: U+%04X",u8"Codepoint: U+%04X")
#define TT_218 AT(u8"是否可见: %d", u8"Visible: %d")
#define TT_219 AT(u8"水平进度: %.1f", u8"AdvanceX: %.1f")
#define TT_220 AT(u8"位置: (%.2f,%.2f)->(%.2f,%.2f)", u8"Pos: (%.2f,%.2f)->(%.2f,%.2f)")
#define TT_221 AT(u8"纹理坐标: (%.3f,%.3f)->(%.3f,%.3f)", u8"UV: (%.3f,%.3f)->(%.3f,%.3f)")
#define TT_222 AT(u8"打开 '%s'",u8"Open '%s'")
#define TT_223 AT(u8"",u8"")
#define TT_224 AT(u8"全局配置###TT_224",u8"Global Setting###TT_224")
#define TT_225 AT(u8"Live2d 全局配置###TT_225",u8"Live2d Global Setting###TT_225")
#define TT_226 AT(u8"置顶不穿透",u8"Top No Touch")
#define TT_227 AT(u8"穿透不置顶",u8"Touch No Top")
#define TT_228 AT(u8"置顶并且穿透",u8"Top And Touch")
#define TT_229 AT(u8"不置顶并且不穿透",u8"No Top No Touch")
#define TT_230 AT(u8"Live2d 的窗体样式",u8"Live2d's window style")
#define TT_231 AT(u8"Windows 全局配置###TT_231",u8"Windows's Global Setting###TT_231")
#define TT_232 AT(u8"Windows 的窗体样式",u8"Windows's window style")
#define TT_233 AT(u8"Windows 的窗体帧率",u8"Windows's window fps")
#define TT_234 AT(u8"不置顶",u8"No Top")
#define TT_235 AT(u8"置顶",u8"Top")
#define TT_236 AT(u8"预估帧率",u8"Predicted frame rate")
#define TT_237 AT(u8"预估插值",u8"Estimated Interpolation")
#define TT_238 AT(u8"实际帧率",u8"Actual frame rate")
#define TT_239 AT(u8"Windows 的窗体停靠",u8"Windows's window dock")
#define TT_240 AT(u8"停靠",u8"Dock")
#define TT_241 AT(u8"不停靠",u8"No Dock")
#define TT_242 AT(u8"停靠时半透明",u8"Docked Translucent")
#define TT_243 AT(u8"停靠时不透明",u8"Docked Nontransparent")
#define TT_244 AT(u8"字体字号大小",u8"Font Pixel Size")
#define TT_245 AT(u8"字体字号",u8"Font Size")
#define TT_246 AT(u8"如果时间未达到目标帧时间间隔，进行短暂的休眠以减少CPU占用。",u8"If the time does not reach the target frame interval, a short sleep is performed to reduce CPU occupation.")
#define TT_247 AT(u8"%d 毫秒",u8"%d ms")
#define TT_248 AT(u8"Live2d 的窗体帧率",u8"Live2d's window fps")
#define TT_249 AT(u8"Live2d 实际帧率(%d FPS)","Live2d frame (%d FPS)")
#define TT_250 AT(u8"Live2d 预估帧率(此项默认系统最大帧率)",u8"Live2d estimated frame rate (the default system maximum frame rate)")
#define TT_251 AT(u8"颜色",u8"Color")
#define TT_252 AT(u8"隐藏标签栏###HideTabBar",u8"Hide tab bar###HideTabBar")
#define TT_253 AT(u8"单击并拖动以移动或取消停靠整个节点。",u8"Click and drag to move or undock whole node.")
#define TT_254 AT(u8"时间日期###TT_254",u8"Time date###TT_254")
#define TT_255 AT(u8"","This is a function that only supports Chinese.")
#define TT_256 AT(u8"从这里开始###TT_256",u8"Start from here###TT_256")
#define TT_257 AT(u8"至少创建一个用户配置实例！",u8"Create at least one user configuration instance!")
#define TT_258 AT(u8"启用交互面板",u8"Enable interactive editor")
#define TT_259 AT(u8"启用虚拟形象",u8"Enable avatar")
#define TT_260 AT(u8"启用设定角色",u8"Enable setting roles")
#define TT_261 AT(u8"启用语音输出(TTS)",u8"Enable voice output(TTS)")
#define TT_262 AT(u8"启用文本翻译(MT)",u8"Enable text translation(MT)")
#define TT_263 AT(u8"启用原文对比",u8"Enable original comparison")
#define TT_264 AT(u8"启用语音输入(STT)",u8"Enable voice input(STT)")
#define TT_265 AT(u8"用户",u8"User")
#define TT_266 AT(u8"置空", u8"Set Null")
#define TT_267 AT(u8"虚拟形象 配置###TT_267",u8"Avatar Setting###TT_267")
#define TT_268 AT(u8"Live2d 选择",u8"Live2d Select")
#define TT_269 AT(u8"空的",u8"NULL")
#define TT_270 AT(u8"调整列宽以适应###SizeOne",u8"Size column to fit###SizeOne")
#define TT_271 AT(u8"调整所有列宽以适应###SizeAll",u8"Size all columns to fit###SizeAll")
#define TT_272 AT(u8"将所有列重置为默认宽度###SizeAll",u8"Size all columns to default###SizeAll")
#define TT_273 AT(u8"重置顺序###ResetOrder",u8"Reset order###ResetOrder")
#define TT_274 AT(u8"高性能模式",u8"Highperformance")
#define TT_275 AT(u8"节能模式","Economize")
#define TT_276 AT(u8"Windows 的窗体渲染功率",u8"Windows's rendering power")
#define TT_277 AT(u8"添加用户",u8"Add User")
#define TT_278 AT(u8"删除用户",u8"Delete User")
#define TT_279 AT(u8"角色 %d###Character%d",u8"Character %d###Character%d")
#define TT_280 AT(u8"大小缩放",u8"Size scaling")
#define TT_281 AT(u8"横轴缩放",u8"Horizontal axis scaling")
#define TT_282 AT(u8"纵轴缩放",u8"Vertical axis scaling")
#define TT_283 AT(u8"水平坐标",u8"Horizontal X")
#define TT_284 AT(u8"垂直坐标",u8"Vertical Y")
#define TT_285 AT(u8"水平拉伸",u8"Horizontal stretching")
#define TT_286 AT(u8"垂直拉伸",u8"Vertical stretching")
#define TT_287 AT(u8"水平透视",u8"Horizontal perspective")
#define TT_288 AT(u8"垂直透视",u8"Vertical perspective")
#define TT_289 AT(u8"预览动画",u8"Preview animation")
#define TT_290 AT(u8"动画", u8"Animation")
#define TT_291 AT(u8"几何", u8"Geometry")
#define TT_292 AT(u8"动画组: ",u8"Animation Group: ")
#define TT_293 AT(u8"重置",u8"Reset")
#define TT_294 AT(u8"重置全部","Reset All")