#pragma once
#include "shinobugui_src/global.h"

#define GETGUIMARK(TT_) ([]() -> const char* { \
    static char buffer[DEFSIZE] = {0}; \
    snprintf(buffer, sizeof(buffer), "%s##%s", TT_, #TT_); \
    return buffer; \
})()

#define GETGUIID(TT_) ([]() -> const char* { \
    static char buffer[DEFSIZE] = {0}; \
    snprintf(buffer, sizeof(buffer), "%s###%s", TT_, #TT_); \
    return buffer; \
})()

#define TT_0 AT(u8"项目关于",u8"Project About",u8"プロジェクトについて")
#define TT_1 AT(u8"这是关于",u8"About the project",u8"プロジェクトについて")
#define TT_2 AT(u8"如果问题未能解决或遇到新的问题请去 Issues。",u8"If the problem can't be solved or you encounter new problems, please go to Issues.",u8"問題が解決しない場合や新しい問題が発生した場合は Issues を参照してください。")
#define TT_3 AT(u8"https://github.com/log159/ShinobuDiary",u8"https://github.com/log159/ShinobuDiary",u8"https://github.com/log159/ShinobuDiary")
#define TT_4 AT(u8"语言选择",u8"Language Select",u8"言語選択")
#define TT_5 AT(u8"语言配置",u8"Language Setting",u8"言語設定")
#define TT_6 AT(u8"LLM 选择",u8"LLM Select",u8"LLM 選択")
#define TT_7 AT(u8"LLM 配置",u8"LLM Setting",u8"LLM 設定")
#define TT_8 AT(u8"保存配置",u8"Save Setting",u8"設定を保存")
#define TT_9 AT(u8"TTS 选择",u8"TTS Select",u8"TTS 選択")
#define TT_10 AT(u8"TTS 配置",u8"TTS Setting",u8"TTS 設定")
#define TT_11 AT(u8"STT 选择",u8"STT Select",u8"STT 選択")
#define TT_12 AT(u8"STT 配置",u8"STT Setting",u8"STT 設定")
#define TT_13 AT(u8"MT 选择",u8"MT Select",u8"MT 選択")
#define TT_14 AT(u8"MT 配置",u8"MT Setting",u8"MT 設定")
#define TT_15 AT(u8"项目帮助",u8"Project Help",u8"プロジェクトヘルプ")
#define TT_16 AT(u8"项目的帮助",u8"Help about the project",u8"プロジェクトのヘルプ")
#define TT_17 AT(u8"查看对应的 (?) 图标得到使用说明。",u8"View the corresponding (?) icon for instructions.",u8"対応する (?) アイコンをクリックして使用方法を確認してください。")
#define TT_18 AT(u8"ChatGPT",u8"ChatGPT",u8"ChatGPT")
#define TT_19 AT(u8"讯飞星火",u8"SparkDesk",u8"SparkDesk")
#define TT_20 AT(u8"深度求索",u8"DeepSeek",u8"DeepSeek")
#define TT_21 AT(u8"vits-simple-api",u8"vits-simple-api",u8"vits-simple-api")
#define TT_22 AT(u8"GPT-SoVits",u8"GPT-SoVits",u8"GPT-SoVits")
#define TT_23 AT(u8"用户自定义的-Vits",u8"MySelf-Vits",u8"ユーザー定義の Vits")
#define TT_24 AT(u8"百度智能云",u8"BaiDuZhiNengYun",u8"百度智能云")
#define TT_25 AT(u8"百度翻译",u8"BaiDufanYi",u8"百度翻訳")
#define TT_26 AT(u8"讲述人编号",u8"speaker Id",u8"話者番号")
#define TT_27 AT(u8"模型选择",u8"model select",u8"モデル選択")
#define TT_28 AT(u8"情感参数(适用于w2v2)",u8"emotional id (for w2v2)",u8"感情パラメータ (w2v2用)")
#define TT_29 AT(u8"目标语言(适用于api2)",u8"target language (for api2)",u8"目標言語 (api2用)")
#define TT_30 AT(u8"https://github.com/jianchang512/gptsovits-api",u8"https://github.com/jianchang512/gptsovits-api",u8"https://github.com/jianchang512/gptsovits-api")
#define TT_31 AT(u8"自定义的请求",u8"custom url",u8"カスタム URL")
#define TT_32 AT(u8"用户配置",u8"User Setting",u8"ユーザー設定")
#define TT_33 AT(u8"用户配置%d",u8"User Setting%d",u8"ユーザー設定%d")
#define TT_34 AT(u8"删除这个用户配置？",u8"Delete this user configuration?",u8"このユーザー設定を削除しますか？")
#define TT_35 AT(u8"删除？",u8"Delete?",u8"削除しますか？")
#define TT_36 AT(u8"是",u8"YES",u8"はい")
#define TT_37 AT(u8"否",u8"NO",u8"いいえ")
#define TT_38 AT(u8"小忍日记 %c %s",u8"ShinobuDiary %c %s",u8"小忍日記 %c %s")
#define TT_39 AT(u8"样式面板",u8"Style Editor",u8"スタイルエディター")
#define TT_40 AT(u8"样式配置",u8"Style Setting",u8"スタイル設定")
#define TT_41 AT(u8"样式面板",u8"Style Editor",u8"スタイルエディター")
#define TT_42 AT(u8"应用程序平均 % .3f毫秒 / 实际帧率(% .1f FPS)","Application average %.3f ms/frame (%.1f FPS)",u8"アプリケーション平均 %.3f ms/フレーム (%.1f FPS)")
#define TT_43 AT(u8"颜色选择器", u8"Colors",u8"カラー選択")
#define TT_44 AT(u8"字体选择器", u8"Fonts",u8"フォント選択")
#define TT_45 AT(u8"框架圆角", u8"FrameRounding",u8"フレームの角丸")
#define TT_46 AT(u8"窗口边框", u8"WindowBorder",u8"ウィンドウ枠")
#define TT_47 AT(u8"框架边框", u8"FrameBorder",u8"フレーム枠")
#define TT_48 AT(u8"弹窗边框", u8"PopupBorder",u8"ポップアップ枠")
#define TT_49 AT(u8"保存样式", u8"Save Style",u8"スタイルを保存")
#define TT_50 AT(u8"恢复默认", u8"Revert Origin",u8"デフォルトに戻す")
#define TT_51 AT(u8"尺寸", u8"Sizes",u8"サイズ")
#define TT_52 AT(u8"主要", u8"Main",u8"主要")
#define TT_53 AT(u8"窗口内边距", u8"WindowPadding",u8"ウィンドウの内余白")
#define TT_54 AT(u8"框架内边距", u8"FramePadding",u8"フレームの内余白")
#define TT_55 AT(u8"元素间距", u8"ItemSpacing",u8"要素間隔")
#define TT_56 AT(u8"元素内间距", u8"ItemInnerSpacing",u8"要素の内余白")
#define TT_57 AT(u8"触控额外内边距", u8"TouchExtraPadding",u8"タッチの追加内余白")
#define TT_58 AT(u8"缩进间距", u8"IndentSpacing",u8"インデント間隔")
#define TT_59 AT(u8"滚动条大小", u8"ScrollbarSize",u8"スクロールバーのサイズ")
#define TT_60 AT(u8"抓取条大小", u8"GrabMinSize",u8"スクロールバーのハンドルサイズ")
#define TT_61 AT(u8"边框", u8"Borders",u8"枠線")
#define TT_62 AT(u8"窗口边框大小", u8"WindowBorderSize",u8"ウィンドウ枠のサイズ")
#define TT_63 AT(u8"子窗口边框大小", u8"ChildBorderSize",u8"子ウィンドウ枠のサイズ")
#define TT_64 AT(u8"弹窗边框大小", u8"PopupBorderSize",u8"ポップアップ枠のサイズ")
#define TT_65 AT(u8"框架边框大小", u8"FrameBorderSize",u8"フレーム枠のサイズ")
#define TT_66 AT(u8"标签边框大小", u8"TabBorderSize",u8"タブ枠のサイズ")
#define TT_67 AT(u8"标签栏边框大小", u8"TabBarBorderSize",u8"タブバー枠のサイズ")
#define TT_68 AT(u8"标签栏上划线大小", u8"TabBarOverlineSize",u8"タブバーの上線のサイズ")
#define TT_69 AT(u8"深色\0浅色\0经典\0", u8"Dark\0Light\0Classic\0",u8"ダーク\0ライト\0クラシック\0")
#define TT_70 AT(u8"圆角", u8"Rounding",u8"角丸")
#define TT_71 AT(u8"窗口圆角", u8"WindowRounding",u8"ウィンドウの角丸")
#define TT_72 AT(u8"子窗口圆角", u8"ChildRounding",u8"子ウィンドウの角丸")
#define TT_73 AT(u8"框架圆角", u8"FrameRounding",u8"フレームの角丸")
#define TT_74 AT(u8"弹窗圆角", u8"PopupRounding",u8"ポップアップの角丸")
#define TT_75 AT(u8"滚动条圆角", u8"ScrollbarRounding",u8"スクロールバーの角丸")
#define TT_76 AT(u8"抓取条圆角", u8"GrabRounding",u8"スクロールバーのハンドルの角丸")
#define TT_77 AT(u8"标签圆角", u8"TabRounding",u8"タブの角丸")
#define TT_78 AT(u8"表格", u8"Tables",u8"テーブル")
#define TT_79 AT(u8"单元格内边距", u8"CellPadding",u8"セルの内余白")
#define TT_80 AT(u8"表格倾斜标题角度", u8"TableAngledHeadersAngle",u8"テーブルの傾斜ヘッダー角度")
#define TT_81 AT(u8"表格倾斜标题文本对齐", u8"TableAngledHeadersTextAlign",u8"テーブルの傾斜ヘッダーのテキスト揃え")
#define TT_82 AT(u8"窗口", u8"Widgets",u8"ウィジェット")
#define TT_83 AT(u8"窗口标题对齐", u8"WindowTitleAlign",u8"ウィンドウタイトルの揃え")
#define TT_84 AT(u8"窗口菜单按钮位置", u8"WindowMenuButtonPosition",u8"ウィンドウメニューボタンの位置")
#define TT_85 AT(u8"无\0左\0右\0", u8"None\0Left\0Right\0",u8"なし\0左\0右\0")
#define TT_86 AT(u8"按钮文本对齐", u8"ButtonTextAlign",u8"ボタンテキストの揃え")
#define TT_87 AT(u8"当按钮大于其文本内容时应用对齐。", u8"Alignment applies when a button is larger than its text content.",u8"ボタンがテキスト内容より大きい場合に揃えを適用します。")
#define TT_88 AT(u8"可选择文本对齐", u8"SelectableTextAlign",u8"選択可能テキストの揃え")
#define TT_89 AT(u8"当可选择项大于其文本内容时应用对齐。", u8"Alignment applies when a selectable is larger than its text content.",u8"選択可能な項目がテキスト内容より大きい場合に揃えを適用します。")
#define TT_90 AT(u8"分隔符文本边框大小", u8"SeparatorTextBorderSize",u8"セパレーターのテキスト枠のサイズ")
#define TT_91 AT(u8"分隔符文本对齐", u8"SeparatorTextAlign",u8"セパレーターのテキスト揃え")
#define TT_92 AT(u8"分隔符文本内边距", u8"SeparatorTextPadding",u8"セパレーターのテキスト内余白")
#define TT_93 AT(u8"对数滑块死区", u8"LogSliderDeadzone",u8"対数スライダーのデッドゾーン")
#define TT_94 AT(u8"停靠", u8"Docking",u8"ドッキング")
#define TT_95 AT(u8"停靠分隔器大小", u8"DockingSplitterSize",u8"ドッキングセパレーターのサイズ")
#define TT_96 AT(u8"工具提示", u8"Tooltips",u8"ツールチップ")
#define TT_97 AT(u8"鼠标悬停工具提示标志", u8"HoverFlagsForTooltipMouse",u8"マウスホバーのツールチップフラグ")
#define TT_98 AT(u8"导航悬停工具提示标志", u8"HoverFlagsForTooltipNav",u8"ナビゲートホバーのツールチップフラグ")
#define TT_99 AT(u8"悬停标志_无延迟", u8"HoveredFlags_DelayNone",u8"ホバーなしの遅延")
#define TT_100 AT(u8"悬停标志_短延迟", u8"HoveredFlags_DelayShort",u8"ホバーの短い遅延")
#define TT_101 AT(u8"悬停标志_正常延迟", u8"HoveredFlags_DelayNormal",u8"ホバーの通常の遅延")
#define TT_102 AT(u8"悬停标志_静止", u8"HoveredFlags_Stationary",u8"ホバーの静止")
#define TT_103 AT(u8"悬停标志_无共享延迟", u8"HoveredFlags_NoSharedDelay",u8"ホバーなしの共有遅延")
#define TT_104 AT(u8"杂项", u8"Misc",u8"その他の")
#define TT_105 AT(u8"显示窗口内边距", u8"DisplayWindowPadding",u8"ウィンドウの内余白を表示")
#define TT_106 AT(u8"显示安全区域内边距", u8"DisplaySafeAreaPadding",u8"安全領域の内余白を表示")
#define TT_107 AT(u8"颜色", u8"Colors",u8"カラー")
#define TT_108 AT(u8"导出", u8"Export",u8"エクスポート")
#define TT_109 AT(u8"到剪贴板\0到终端设备\0", u8"To Clipboard\0To TTY\0",u8"クリップボードに\0端末に\0")
#define TT_110 AT(u8"仅修改颜色", u8"Only Modified Colors",u8"変更されたカラーのみ")
#define TT_111 AT(u8"筛选颜色", u8"Filter colors",u8"カラーをフィルター")
#define TT_112 AT(u8"不透明", u8"Opaque",u8"不透明")
#define TT_113 AT(u8"透明度", u8"Alpha",u8"透明度")
#define TT_114 AT(u8"混合的", u8"Both",u8"両方")
#define TT_115 AT(u8"在颜色列表中：\n左键单击颜色方块以打开颜色选择器，\n右键单击打开编辑选项菜单。", u8"In the color list:\nLeft-click on color square to open color picker,\nRight-click to open edit options menu.",u8"カラーのリストで：\nカラーの四角を左クリックしてカラーピッカーを開く、\n右クリックして編集オプションメニューを開く。")
#define TT_116 AT(u8"闪烁指定颜色以标识其使用位置。", u8"Flash given color to identify places where it is used.",u8"指定のカラーを点滅させて使用場所を識別する。")
#define TT_117 AT(u8"保存", u8"Save",u8"保存")
#define TT_118 AT(u8"恢复", u8"Revert",u8"元に戻す")
#define TT_119 AT(u8"字体", u8"Fonts",u8"フォント")
#define TT_120 AT(u8"窗口缩放", u8"Window scale",u8"ウィンドウのスケール")
#define TT_121 AT(u8"全局缩放", u8"Global scale",u8"全体のスケール")
#define TT_122 AT(u8"渲染", u8"Rendering",u8"レンダリング")
#define TT_123 AT(u8"抗锯齿线", u8"Anti-aliased lines",u8"アンチエイリアシングされたライン")
#define TT_124 AT(u8"抗锯齿线使用纹理", u8"Anti-aliased lines use texture",u8"アンチエイリアシングされたラインはテクスチャを使用する")
#define TT_125 AT(u8"抗锯齿填充", u8"Anti-aliased fill",u8"アンチエイリアシングされたフィル")
#define TT_126 AT(u8"曲线细分容差", u8"Curve Tessellation Tolerance",u8"曲線の細分割許容誤差")
#define TT_127 AT(u8"圆形细分最大误差", u8"Circle Tessellation Max Error",u8"円形の細分割最大誤差")
#define TT_128 AT(u8"%.0f 度", u8"%.0f deg",u8"%.0f 度")
#define TT_129 AT(u8"全局透明度", u8"Global Alpha",u8"全体の透明度")
#define TT_130 AT(u8"禁用透明度", u8"Disabled Alpha",u8"無効な透明度")
#define TT_131 AT(u8"为禁用项添加的额外透明度乘数(在当前 Alpha 值基础上叠加)。", u8"Additional alpha multiplier for disabled items (multiply over current value of Alpha).",u8"無効な項目に追加される透明度の倍率(現在の Alpha 値に重ね合わせる)。")
#define TT_132 AT(u8"颜色按钮位置",u8"ColorButtonPosition",u8"カラーのボタンの位置")
#define TT_133 AT(u8"左\0右\0", "Left\0Right\0",u8"左\0右\0")
#define TT_134 AT(u8"应用于常规窗口:当移动到屏幕边缘附近时，我们强制保持可见的量。",u8"Apply to regular windows: amount which we enforce to keep visible when moving near edges of your screen.",u8"通常のウィンドウに適用：画面の端に近づいたとき、強制的に表示する量。")
#define TT_135 AT(u8"适用于每个窗口，菜单，弹出窗口，工具提示:我们避免显示内容的数量。如果看不到屏幕边缘，请进行调整(例如，在未配置缩放的TV)。","Apply to every windows, menus, popups, tooltips: amount where we avoid displaying contents. Adjust if you cannot see the edges of your screen (e.g. on a TV where scaling has not been configured).",u8"すべてのウィンドウ、メニュー、ポップアップ、ツールチップに適用：表示を避ける量。画面の端が見えていない場合は調整してください(例えば、スケール設定がされていないテレビなど)。")
#define TT_136 AT(u8"文本", u8"Text",u8"テキスト")
#define TT_137 AT(u8"问号提示文本", u8"TextDisabled",u8"質問マークの説明テキスト")
#define TT_138 AT(u8"窗口背景", u8"WindowBg",u8"ウィンドウの背景")
#define TT_139 AT(u8"子窗口背景", u8"ChildBg",u8"子ウィンドウの背景")
#define TT_140 AT(u8"弹窗背景", u8"PopupBg",u8"ポップアップの背景")
#define TT_141 AT(u8"边框", u8"Border",u8"枠線")
#define TT_142 AT(u8"边框阴影", u8"BorderShadow",u8"枠線の影")
#define TT_143 AT(u8"框架背景", u8"FrameBg",u8"フレームの背景")
#define TT_144 AT(u8"框架背景悬停", u8"FrameBgHovered",u8"フレームの背景(ホバー時)")
#define TT_145 AT(u8"框架背景激活", u8"FrameBgActive",u8"フレームの背景(活性化時)")
#define TT_146 AT(u8"标题背景", u8"TitleBg",u8"タイトルの背景")
#define TT_147 AT(u8"标题背景激活", u8"TitleBgActive",u8"タイトルの背景(活性化時)")
#define TT_148 AT(u8"标题背景折叠", u8"TitleBgCollapsed",u8"タイトルの背景(折り畳み時)")
#define TT_149 AT(u8"菜单栏背景", u8"MenuBarBg",u8"メニューバーの背景")
#define TT_150 AT(u8"滚动条背景", u8"ScrollbarBg",u8"スクロールバーの背景")
#define TT_151 AT(u8"滚动条抓取", u8"ScrollbarGrab",u8"スクロールバーのハンドル")
#define TT_152 AT(u8"滚动条抓取悬停", u8"ScrollbarGrabHovered",u8"スクロールバーのハンドル(ホバー時)")
#define TT_153 AT(u8"滚动条抓取激活", u8"ScrollbarGrabActive",u8"スクロールバーのハンドル(活性化時)")
#define TT_154 AT(u8"勾选标记", u8"CheckMark",u8"チェックマーク")
#define TT_155 AT(u8"滑块抓取", u8"SliderGrab",u8"スライダーのハンドル")
#define TT_156 AT(u8"滑块抓取激活", u8"SliderGrabActive",u8"スライダーのハンドル(活性化時)")
#define TT_157 AT(u8"按钮", u8"Button",u8"ボタン")
#define TT_158 AT(u8"按钮悬停", u8"ButtonHovered",u8"ボタン(ホバー時)")
#define TT_159 AT(u8"按钮激活", u8"ButtonActive",u8"ボタン(活性化時)")
#define TT_160 AT(u8"标题", u8"Header",u8"ヘッダー")
#define TT_161 AT(u8"标题悬停", u8"HeaderHovered",u8"ヘッダー(ホバー時)")
#define TT_162 AT(u8"标题激活", u8"HeaderActive",u8"ヘッダー(活性化時)")
#define TT_163 AT(u8"分隔符", u8"Separator",u8"セパレーター")
#define TT_164 AT(u8"分隔符悬停", u8"SeparatorHovered",u8"セパレーター(ホバー時)")
#define TT_165 AT(u8"分隔符激活", u8"SeparatorActive",u8"セパレーター(活性化時)")
#define TT_166 AT(u8"调整大小抓取", u8"ResizeGrip",u8"サイズ変更のハンドル")
#define TT_167 AT(u8"调整大小抓取悬停", u8"ResizeGripHovered",u8"サイズ変更のハンドル(ホバー時)")
#define TT_168 AT(u8"调整大小抓取激活", u8"ResizeGripActive",u8"サイズ変更のハンドル(活性化時)")
#define TT_169 AT(u8"标签悬停", u8"TabHovered",u8"タブ(ホバー時)")
#define TT_170 AT(u8"标签", u8"Tab",u8"タブ")
#define TT_171 AT(u8"选中的标签", u8"TabSelected",u8"選択されたタブ")
#define TT_172 AT(u8"选中的标签上划线", u8"TabSelectedOverline",u8"選択されたタブの上線")
#define TT_173 AT(u8"标签变暗", u8"TabDimmed",u8"タブを暗くする")
#define TT_174 AT(u8"选中的标签变暗", u8"TabDimmedSelected",u8"選択されたタブを暗くする")
#define TT_175 AT(u8"选中的标签变暗上划线", u8"TabDimmedSelectedOverline",u8"選択されたタブを暗くする(上線)")
#define TT_176 AT(u8"停靠预览", u8"DockingPreview",u8"ドッキングプレビュー")
#define TT_177 AT(u8"停靠空背景", u8"DockingEmptyBg",u8"ドッキングの空の背景")
#define TT_178 AT(u8"绘图线", u8"PlotLines",u8"プロットライン")
#define TT_179 AT(u8"绘图线悬停", u8"PlotLinesHovered",u8"プロットライン(ホバー時)")
#define TT_180 AT(u8"绘图直方图", u8"PlotHistogram",u8"プロットヒストグラム")
#define TT_181 AT(u8"绘图直方图悬停", u8"PlotHistogramHovered",u8"プロットヒストグラム(ホバー時)")
#define TT_182 AT(u8"表头背景", u8"TableHeaderBg",u8"テーブルヘッダーの背景")
#define TT_183 AT(u8"表格强边框", u8"TableBorderStrong",u8"テーブルの強い枠線")
#define TT_184 AT(u8"表格弱边框", u8"TableBorderLight",u8"テーブルの弱い枠線")
#define TT_185 AT(u8"表格行背景", u8"TableRowBg",u8"テーブルの行の背景")
#define TT_186 AT(u8"表格行背景交替", u8"TableRowBgAlt",u8"テーブルの行の背景(交互)")
#define TT_187 AT(u8"文本链接", u8"TextLink",u8"テキストリンク")
#define TT_188 AT(u8"选中文本背景", u8"TextSelectedBg",u8"選択されたテキストの背景")
#define TT_189 AT(u8"拖放目标", u8"DragDropTarget",u8"ドラッグアンドドロップのターゲット")
#define TT_190 AT(u8"导航光标", u8"NavCursor",u8"ナビゲートカーソル")
#define TT_191 AT(u8"导航窗口高亮", u8"NavWindowingHighlight",u8"ナビゲートウィンドウのハイライト")
#define TT_192 AT(u8"导航窗口背景变暗", u8"NavWindowingDimBg",u8"ナビゲートウィンドウの背景を暗くする")
#define TT_193 AT(u8"模态窗口背景变暗", u8"ModalWindowDimBg",u8"モーダルウィンドウの背景を暗くする")
#define TT_194 AT(u8"未知的",u8"Unknown",u8"不明")
#define TT_195 AT(u8"当禁用抗锯齿线条时，您可能还想禁用样式中的边框。", u8"When disabling anti - aliasing lines, you'll probably want to disable borders in your style as well.",u8"アンチエイリアシングされたラインを無効にした場合、スタイルの枠線も無効にしたいかもしれません。")
#define TT_196 AT(u8"更快的线条使用纹理数据。要求后端使用双线性过滤进行渲染(不是点/最近过滤)。",u8"Faster lines using texture data. Require backend to render with bilinear filtering (not point/nearest filtering).",u8"より速いラインはテクスチャデータを使用します。バックエンドはバイリニアフィルタリング(ポイント/ニアレストフィルタリングではなく)を使用してレンダリングする必要があります。")
#define TT_197 AT(u8"(R =半径，N =分段的大概数量)",u8"(R = radius, N = approx number of segments)",u8"(R = 半径、N = 分割の概数)")
#define TT_198 AT(u8"字体: \"%s\"\n%.2f 像素, %d 字形, %d 个文件(s)",u8"Font: \"%s\"\n%.2f px, %d glyphs, %d file(s)",u8"フォント: \"%s\"\n%.2f px, %d グリフ, %d ファイル(s)")
#define TT_199 AT(u8"设为默认值",u8"Set as default",u8"デフォルトとして設定")
#define TT_200 AT(u8"那只敏捷的棕色狐狸跳过了那只懒狗",u8"The quick brown fox jumps over the lazy dog",u8"素早い茶色の狐は怠け者の犬を飛び越える")
#define TT_201 AT(u8"字体比例",u8"Font scale",u8"フォントのスケール")
#define TT_202 AT(u8"上升:%f，下降:%f，高度:%f",u8"Ascent: %f, Descent: %f, Height: %f",u8"上昇:%f、下降:%f、高さ:%f")
#define TT_203 AT(u8"回退字符: '%s' (U+%04X)",u8"Fallback character: '%s' (U+%04X)",u8"フォールバックキャラクター: '%s' (U+%04X)")
#define TT_204 AT(u8"省略号字符: '%s' (U+%04X)",u8"Ellipsis character: '%s' (U+%04X)",u8"省略記号キャラクター: '%s' (U+%04X)")
#define TT_205 AT(u8"纹理区域:关于 %d 像素 ~%dx%d 像素",u8"Texture Area: about %d px ~%dx%d px",u8"テクスチャ領域: 約 %d px ~%dx%d px")
#define TT_206 AT(u8"输入%d: \'%s\'，过采样:(%d，%d)，像素快照: %d，偏移量:(%.1f，%.1f)",u8"Input %d: \'%s\', Oversample: (%d,%d), PixelSnapH: %d, Offset: (%.1f,%.1f)",u8"入力%d: \'%s\'、オーバーサンプリング:(%d、%d)、ピクセルスナップ:%d、オフセット:(%.1f、%.1f)")
#define TT_207 AT(u8"字形",u8"Glyphs",u8"グリフ")
#define TT_208 AT(u8"字形 (%d)",u8"Glyphs (%d)",u8"グリフ (%d)")
#define TT_209 AT(u8"字形",u8"glyphs",u8"グリフ")
#define TT_210 AT(u8"字形",u8"glyph",u8"グリフ")
#define TT_211 AT(u8"字体图集",u8"Font Atlas",u8"フォントアトラス")
#define TT_212 AT(u8"字体图集 (%dx%d 像素)",u8"Font Atlas (%dx%d pixels)",u8"フォントアトラス (%dx%d ピクセル)")
#define TT_213 AT(u8"应用文字颜色渲染",u8"Tint with Text Color",u8"テキストカラーで塗りつぶし")
#define TT_214 AT(u8"复制为..",u8"Copy as..",u8"コピーする...")
#define TT_215 AT(u8"当前的",u8"Current",u8"現在の")
#define TT_216 AT(u8"原来的",u8"Original",u8"元の")
#define TT_217 AT(u8"字符码点: U+%04X",u8"Codepoint: U+%04X",u8"文字コードポイント: U+%04X")
#define TT_218 AT(u8"是否可见: %d", u8"Visible: %d",u8"可視性: %d")
#define TT_219 AT(u8"水平进度: %.1f", u8"AdvanceX: %.1f",u8"水平進行: %.1f")
#define TT_220 AT(u8"位置: (%.2f,%.2f)->(%.2f,%.2f)", u8"Pos: (%.2f,%.2f)->(%.2f,%.2f)",u8"位置: (%.2f,%.2f)->(%.2f,%.2f)")
#define TT_221 AT(u8"纹理坐标: (%.3f,%.3f)->(%.3f,%.3f)", u8"UV: (%.3f,%.3f)->(%.3f,%.3f)",u8"テクスチャ座標: (%.3f,%.3f)->(%.3f,%.3f)")
#define TT_222 AT(u8"打开 '%s'",u8"Open '%s'",u8"'%s'を開く")
#define TT_223 AT(u8"",u8"",u8"")
#define TT_224 AT(u8"全局配置",u8"Global Setting",u8"グローバル設定")
#define TT_225 AT(u8"Live2d 全局配置",u8"Live2d Global Setting",u8"Live2dのグローバル設定")
#define TT_226 AT(u8"置顶不穿透",u8"Top No Touch",u8"トップで透過しない")
#define TT_227 AT(u8"穿透不置顶",u8"Touch No Top",u8"透過するがトップでない")
#define TT_228 AT(u8"置顶并且穿透",u8"Top And Touch",u8"トップで透過する")
#define TT_229 AT(u8"不置顶并且不穿透",u8"No Top No Touch",u8"トップでないし透過しない")
#define TT_230 AT(u8"Live2d 的窗体样式",u8"Live2d's window style",u8"Live2dのウィンドウスタイル")
#define TT_231 AT(u8"Windows 全局配置",u8"Windows's Global Setting",u8"Windowsのグローバル設定")
#define TT_232 AT(u8"Windows 的窗体样式",u8"Windows's style",u8"Windowsのウィンドウスタイル")
#define TT_233 AT(u8"Windows 的窗体帧率",u8"Windows's fps",u8"Windowsのウィンドウフレームレート")
#define TT_234 AT(u8"不置顶",u8"No Top",u8"トップでない")
#define TT_235 AT(u8"置顶",u8"Top",u8"トップ")
#define TT_236 AT(u8"预估帧率",u8"Predicted frame rate",u8"予測フレームレート")
#define TT_237 AT(u8"预估插值",u8"Estimated interpolation",u8"推定補間")
#define TT_238 AT(u8"实际帧率",u8"Actual frame rate",u8"実際のフレームレート")
#define TT_239 AT(u8"Windows 的窗体停靠",u8"Windows's dock",u8"Windowsのウィンドウドッキング")
#define TT_240 AT(u8"停靠",u8"Dock",u8"ドッキング")
#define TT_241 AT(u8"不停靠",u8"No Dock",u8"ドッキングしない")
#define TT_242 AT(u8"停靠时半透明",u8"Docked Translucent",u8"ドッキング時に半透明")
#define TT_243 AT(u8"停靠时不透明",u8"Docked Nontransparent",u8"ドッキング時に不透明")
#define TT_244 AT(u8"字体字号大小",u8"Font Pixel Size",u8"フォントのピクセルサイズ")
#define TT_245 AT(u8"字体字号",u8"Font Size",u8"フォントサイズ")
#define TT_246 AT(u8"如果时间未达到目标帧时间间隔，进行短暂的休眠以减少CPU占用。",u8"If the time does not reach the target frame interval, a short sleep is performed to reduce CPU occupation.",u8"時間間隔が目標フレーム間隔に達しない場合、CPU使用量を減らすために短時間のスリープを行います。")
#define TT_247 AT(u8"%d 毫秒",u8"%d ms",u8"%d ミリ秒")
#define TT_248 AT(u8"Live2d 的窗体帧率",u8"Live2d's window fps",u8"Live2dのウィンドウフレームレート")
#define TT_249 AT(u8"Live2d 实际帧率(%d FPS)","Live2d frame (%d FPS)",u8"Live2dの実際のフレームレート(%d FPS)")
#define TT_250 AT(u8"Live2d 预估帧率(此项默认系统最大帧率)",u8"Live2d estimated frame rate (the default system maximum frame rate)",u8"Live2dの予測フレームレート(デフォルトはシステムの最大フレームレート)")
#define TT_251 AT(u8"颜色",u8"Color",u8"カラー")
#define TT_252 AT(u8"隐藏标签栏",u8"Hide tab bar",u8"タブバーを隠す")
#define TT_253 AT(u8"单击并拖动以移动或取消停靠整个节点。",u8"Click and drag to move or undock whole node.",u8"クリックしてドラッグして、ノード全体を移動またはドッキングを解除します。")
#define TT_254 AT(u8"时间日期",u8"Time date",u8"日付と時間")
#define TT_255 AT(u8"",u8"",u8"")
#define TT_256 AT(u8"从这里开始",u8"Start from here",u8"ここから始める")
#define TT_257 AT(u8"至少创建一个用户配置实例！",u8"Create at least one user configuration instance!",u8"少なくとも1つのユーザーコンフィギュレーションインスタンスを作成する必要があります！")
#define TT_258 AT(u8"启用交互面板",u8"Enable interactive editor",u8"インタラクティブエディターを有効にする")
#define TT_259 AT(u8"启用虚拟形象",u8"Enable avatar",u8"アバターを有効にする")
#define TT_260 AT(u8"启用设定角色",u8"Enable setting roles",u8"役割設定を有効にする")
#define TT_261 AT(u8"启用语音输出(TTS)",u8"Enable voice output(TTS)",u8"音声出力(TTS)を有効にする")
#define TT_262 AT(u8"启用文本翻译(MT)",u8"Enable text translation(MT)",u8"テキスト翻訳(MT)を有効にする")
#define TT_263 AT(u8"启用原文对比",u8"Enable original comparison",u8"原文比較を有効にする")
#define TT_264 AT(u8"启用语音输入(STT)",u8"Enable voice input(STT)",u8"音声入力(STT)を有効にする")
#define TT_265 AT(u8"用户",u8"User",u8"ユーザー")
#define TT_266 AT(u8"置空", u8"Set Null",u8"空にする")
#define TT_267 AT(u8"虚拟形象 配置",u8"Avatar Setting",u8"アバター設定")
#define TT_268 AT(u8"Live2d 选择",u8"Live2d Select",u8"Live2d選択")
#define TT_269 AT(u8"空的",u8"NULL",u8"空")
#define TT_270 AT(u8"调整列宽以适应",u8"Size column to fit",u8"列の幅を調整してフィットする")
#define TT_271 AT(u8"调整所有列宽以适应",u8"Size all columns to fit",u8"すべての列の幅を調整してフィットする")
#define TT_272 AT(u8"将所有列重置为默认宽度",u8"Size all columns to default",u8"すべての列をデフォルトの幅に戻す")
#define TT_273 AT(u8"重置顺序",u8"Reset order",u8"順序をリセットする")
#define TT_274 AT(u8"高性能模式",u8"Highperformance",u8"高性能モード")
#define TT_275 AT(u8"节能模式","Economize",u8"節電モード")
#define TT_276 AT(u8"Windows 的窗体渲染功率",u8"Windows's rendering power",u8"Windowsのウィンドウレンダリングパワー")
#define TT_277 AT(u8"添加用户",u8"Add User",u8"ユーザーを追加する")
#define TT_278 AT(u8"删除用户",u8"Delete User",u8"ユーザーを削除する")
#define TT_279 AT(u8"角色 %d",u8"Character %d",u8"キャラクター %d")
#define TT_280 AT(u8"大小缩放",u8"Size scaling",u8"サイズスケーリング")
#define TT_281 AT(u8"横轴缩放",u8"Horizontal axis scaling",u8"水平軸スケーリング")
#define TT_282 AT(u8"纵轴缩放",u8"Vertical axis scaling",u8"垂直軸スケーリング")
#define TT_283 AT(u8"水平坐标",u8"Horizontal x",u8"水平座標")
#define TT_284 AT(u8"垂直坐标",u8"Vertical y",u8"垂直座標")
#define TT_285 AT(u8"水平拉伸",u8"Horizontal stretching",u8"水平方向に引き伸ばす")
#define TT_286 AT(u8"垂直拉伸",u8"Vertical stretching",u8"垂直方向に引き伸ばす")
#define TT_287 AT(u8"水平透视",u8"Horizontal perspective",u8"水平方向の透視図")
#define TT_288 AT(u8"垂直透视",u8"Vertical perspective",u8"垂直方向の透視図")
#define TT_289 AT(u8"预览动画",u8"Preview Animation",u8"アニメーションプレビュー")
#define TT_290 AT(u8"动画", u8"Animation",u8"アニメーション")
#define TT_291 AT(u8"几何", u8"Geometry",u8"ジオメトリ")
#define TT_292 AT(u8"动画组: ",u8"Animation Group: ",u8"アニメーショングループ: ")
#define TT_293 AT(u8"重置",u8"Reset",u8"リセット")
#define TT_294 AT(u8"重置全部","Reset All",u8"すべてリセット")
#define TT_295 AT(u8"看向鼠标",u8"Looking mouse",u8"マウスを向く")
#define TT_296 AT(u8"启用看向鼠标", u8"Enable look mouse",u8"マウスを向く機能を有効にする")
#define TT_297 AT(u8"看向鼠标阻尼系数", u8"Looking damping coefficient",u8"マウスを向く減衰係数")
#define TT_298 AT(u8"系数越大,看向鼠标速度越慢。","The larger the coefficient, the slower the speed of looking at the mouse.",u8"係数が大きいほど、マウスを向く速度が遅くなります。")
#define TT_299 AT(u8"配置看向鼠标详细",u8"Setting looking mouse detailed",u8"マウスを向く設定の詳細")
#define TT_300 AT(u8"参数名称",u8"Parameter Name",u8"パラメーター名")
#define TT_301 AT(u8"系数启用",u8"Factor Enable",u8"係数を有効にする")
#define TT_302 AT(u8"系数大小", u8"Factor Size",u8"係数の大きさ")
#define TT_303 AT(u8"中心轴", u8"Central Axis",u8"中心軸")
#define TT_304 AT(u8"启用",u8"Enable",u8"有効にする")
#define TT_305 AT(u8"大小",u8"Size",u8"サイズ")
#define TT_306 AT(u8"轴",u8"Axis",u8"軸")
#define TT_307 AT(u8"呼吸",u8"Breath",u8"呼吸")
#define TT_308 AT(u8"启用呼吸",u8"Enable breath",u8"呼吸を有効にする")
#define TT_309 AT(u8"配置呼吸详细",u8"Setting breath detailed",u8"呼吸設定の詳細")
#define TT_310 AT(u8"系数偏移量",u8"Factor Offset",u8"係数のオフセット")
#define TT_311 AT(u8"系数最大值",u8"Factor Max",u8"係数の最大値")
#define TT_312 AT(u8"系数周期",u8"Factor Cycle",u8"係数の周期")
#define TT_313 AT(u8"系数权重",u8"Factor Weight",u8"係数のウェイト")
#define TT_314 AT(u8"偏移量",u8"Offset",u8"オフセット")
#define TT_315 AT(u8"最大值",u8"Max Value",u8"最大値")
#define TT_316 AT(u8"周期",u8"Cycle",u8"周期")
#define TT_317 AT(u8"权重",u8"Weight",u8"ウェイト")
#define TT_318 AT(u8"编号",u8"Id",u8"番号")
#define TT_319 AT(u8"眨眼",u8"Blink",u8"まばたき")
#define TT_320 AT(u8"启用眨眼",u8"Enable blink",u8"まばたきを有効にする")
#define TT_321 AT(u8"干涉参数:\n",u8"Interference parameter:\n",u8"干渉パラメーター:\n")
#define TT_322 AT(u8"(空的)",u8"(NULL)",u8"(空)")
#define TT_323 AT(u8"眨眼的时间间隔",u8"Blinking time interval",u8"まばたきの時間間隔")
#define TT_324 AT(u8"闭眼所需的时间",u8"Closing time interval",u8"目を閉じるのにかかる時間")
#define TT_325 AT(u8"完全闭合状态的持续时间",u8"Closed duration time",u8"完全に閉じた状態の持続時間")
#define TT_326 AT(u8"闭合到完全睁开的过渡时间",u8"Transition time from closing to full opening",u8"閉じた状態から完全に開くまでの移行時間")
#define TT_327 AT(u8"配置眨眼详细",u8"Setting blink detailed",u8"まばたき設定の詳細")
#define TT_328 AT(u8"动作动画预览详细",u8"Motion animation preview detailed",u8"動作アニメーションプレビューの詳細")
#define TT_329 AT(u8"表情动画预览详细",u8"Expression animation preview detailed",u8"表情アニメーションプレビューの詳細")
#define TT_330 AT(u8"随机动作动画",u8"Random Motion",u8"ランダムな動作アニメーション")
#define TT_331 AT(u8"随机表情动画",u8"Random Expression",u8"ランダムな表情アニメーション")
#define TT_332 AT(u8"模型渲染配置",u8"Model rendering configuration",u8"モデルレンダリング設定")
#define TT_333 AT(u8"启用正片叠底",u8"Enable multiply colors",u8"正片叠底を有効にする")
#define TT_334 AT(u8"启用屏幕色",u8"Enable screen colors",u8"スクリーンカラーを有効にする")
#define TT_335 AT(u8"正片叠底",u8"Multiply Colors",u8"正片叠底")
#define TT_336 AT(u8"正片叠底详细",u8"Multiply colors detailed",u8"正片叠底の詳細")
#define TT_337 AT(u8"屏幕色",u8"Screen Colors",u8"スクリーンカラー")
#define TT_338 AT(u8"屏幕色详细",u8"Screen colors detailed",u8"スクリーンカラーの詳細")
#define TT_339 AT(u8"正片叠底组","Multiply Colors Group",u8"正片叠底グループ")
#define TT_340 AT(u8"正片叠底组详细","Multiply colors group detailed",u8"正片叠底グループの詳細")
#define TT_341 AT(u8"覆盖全部",u8"Cover All",u8"すべてを覆う")
#define TT_342 AT(u8"覆盖",u8"Cover",u8"覆う")
#define TT_343 AT(u8"屏幕色组",u8"Screen Colors Group",u8"スクリーンカラー グループ")
#define TT_344 AT(u8"屏幕色组详细",u8"Screen colors group detailed",u8"スクリーンカラー グループの詳細")
#define TT_345 AT(u8"Cubism 没有执行!",u8"Cubism not running!",u8"Cubismが実行されていません！")
#define TT_346 AT(u8"发生了错误",u8"An error occurred",u8"エラーが発生しました")
#define TT_347 AT(u8"可选项",u8"Optional",u8"オプション")
#define TT_348 AT(u8"已选项",u8"Selected",u8"選択済み")
#define TT_349 AT(u8"触发",u8"Hit",u8"トリガー")
#define TT_350 AT(u8"预览触发区域",u8"Preview hitareas",u8"トリガー領域のプレビュー")
#define TT_351 AT(u8"触发编号: ",u8"Hit id: ",u8"トリガー番号: ")
#define TT_352 AT(u8"触发名称: ",u8"Hit name: ",u8"トリガー名: ")
#define TT_353 AT(u8"触发计数: ",u8"Hit count: ",u8"トリガー回数: ")
#define TT_354 AT(u8"触发动作: ",u8"Hit motion: ",u8"トリガー動作: ")
#define TT_355 AT(u8"触发表情: ",u8"Hit expression: ",u8"トリガー表情: ")
#define TT_356 AT(u8"名称:",u8"Name:",u8"名前:")
#define TT_357 AT(u8"动作触发",u8"Motion Hit",u8"動作トリガー")
#define TT_358 AT(u8"表情触发",u8"Expression Hit",u8"表情トリガー")
#define TT_359 AT(u8"启用随机自动播放",u8"Enable random autoplay",u8"ランダム自動再生を有効にする")
#define TT_360 AT(u8"启用剔除规则",u8"Enable cullings rule",u8"除去ルールを有効にする")
#define TT_361 AT(u8"全不覆盖",u8"Uncovered All",u8"すべて覆われていない")
#define TT_362 AT(u8"调节颜色",u8"Adjust Color",u8"色を調整する")
#define TT_363 AT(u8"同步全部",u8"Synchronize All",u8"すべてを同期する")
#define TT_364 AT(u8"调试面板",u8"Debug Editor",u8"デバッグエディター")
#define TT_365 AT(u8"功能选择",u8"Function Select",u8"機能選択")
#define TT_366 AT(u8"几何",u8"Geometry",u8"ジオメトリ")
#define TT_367 AT(u8"看向",u8"Look",u8"見る方向")
#define TT_368 AT(u8"呼吸",u8"Breath",u8"呼吸")
#define TT_369 AT(u8"眨眼",u8"Blink",u8"まばたき")
#define TT_370 AT(u8"动画",u8"Animation",u8"アニメーション")
#define TT_371 AT(u8"触发",u8"Hitareas",u8"トリガー領域")
#define TT_372 AT(u8"渲染",u8"Rendering",u8"レンダリング")
#define TT_373 AT(u8"启用触发区域",u8"Enable hitareas",u8"トリガー領域を有効にする")
#define TT_374 AT(u8"当前动作动画: ",u8"Current motion: ",u8"現在の動作アニメーション: ")
#define TT_375 AT(u8"当前表情动画: ",u8"Current expression: ",u8"現在の表情アニメーション: ")
#define TT_376 AT(u8"观测",u8"Observe",u8"観測")
#define TT_377 AT(u8"观测界面",u8"Observation interface",u8"観測インターフェース")
#define TT_378 AT(u8"历史", u8"History",u8"履歴")
#define TT_379 AT(u8"%.1f 秒", u8"%.1f s",u8"%.1f 秒")
#define TT_380 AT(u8"参数解释",u8"Parameter Explain",u8"パラメーターの説明")
#define TT_381 AT(u8"透明组",u8"Opacity Group",u8"透明グループ")
#define TT_382 AT(u8"透明组详细",u8"Opacity group detailed",u8"透明グループの詳細")
#define TT_383 AT(u8"调节透明", u8"Adjust Opacity",u8"透明度を調整する")
#define TT_384 AT(u8"角色 %d 观测",u8"Character %d Observe",u8"キャラクター %d の観測")
#define TT_385 AT(u8"分离窗体",u8"Separate Window",u8"ウィンドウを分離する")
#define TT_386 AT(u8"X-轴",u8"X-Axis",u8"X-軸")
#define TT_387 AT(u8"X-轴 %d",u8"X-Axis %d",u8"X-軸 %d")
#define TT_388 AT(u8"Y-轴",u8"Y-Axis",u8"Y-軸")
#define TT_389 AT(u8"Y-轴 %d",u8"Y-Axis %d",u8"Y-軸 %d")
#define TT_390 AT(u8"鼠标 X",u8"Mouse X",u8"マウス X")
#define TT_391 AT(u8"鼠标 Y",u8"Mouse Y",u8"マウス Y")
#define TT_392 AT(u8"图例",u8"Legend",u8"凡例")
#define TT_393 AT(u8"设置",u8"Settings",u8"設定")
#define TT_394 AT(u8"等比",u8"Equal",u8"等比")
#define TT_395 AT(u8"框选",u8"Box Select",u8"枠選択")
#define TT_396 AT(u8"标题",u8"Title",u8"タイトル")
#define TT_397 AT(u8"鼠标位置",u8"Mouse Position",u8"マウスの位置")
#define TT_398 AT(u8"十字准星",u8"Crosshairs",u8"十字照準器")
#define TT_399 AT(u8"展示",u8"Show",u8"表示する")
#define TT_400 AT(u8"置外",u8"Outside",u8"外側")
#define TT_401 AT(u8"水平",u8"H",u8"水平")
#define TT_402 AT(u8"垂直",u8"V",u8"垂直")
#define TT_403 AT(u8"西北", u8"NW",u8"北西")
#define TT_404 AT(u8"北", u8"N",u8"北")
#define TT_405 AT(u8"东北", u8"NE",u8"北東")
#define TT_406 AT(u8"西", u8"W",u8"西")
#define TT_407 AT(u8"东", u8"E",u8"東")
#define TT_408 AT(u8"西南", u8"SW",u8"南西")
#define TT_409 AT(u8"南", u8"S",u8"南")
#define TT_410 AT(u8"东南", u8"SE",u8"南東")
#define TT_411 AT(u8"中心",u8"C",u8"中央")
#define TT_412 AT(u8"最小", u8"Min",u8"最小")
#define TT_413 AT(u8"最大", u8"Max",u8"最大")
#define TT_414 AT(u8"自动适应", u8"Auto-Fit",u8"自動適合")
#define TT_415 AT(u8"反转", u8"Invert",u8"反転")
#define TT_416 AT(u8"反向", u8"Opposite",u8"反対方向")
#define TT_417 AT(u8"标签", u8"Label",u8"ラベル")
#define TT_418 AT(u8"网格线", u8"Grid Lines",u8"グリッド線")
#define TT_419 AT(u8"刻度线", u8"Tick Marks",u8"目盛り線")
#define TT_420 AT(u8"刻度标签", u8"Tick Labels",u8"目盛りラベル")
#define TT_421 AT(u8"项目地址",u8"Project Address",u8"プロジェクトアドレス")
#define TT_422 AT(u8"筛选参数",u8"Filter parameter",u8"フィルター設定")
#define TT_423 AT(u8"筛选渲染",u8"Filter rendering",u8"フィルターレンダリング")
#define TT_424 AT(u8"筛选渲染组",u8"Filter rendering group",u8"フィルターレンダリンググループ")
#define TT_425 AT(u8"程序正在运行...",u8"The program is running...",u8"プログラムが実行中...")
#define TT_426 AT(u8"退出",u8"Exit",u8"終了")
#define TT_427 AT(u8"显示窗体", u8"Show Window", u8"ウィンドウを表示")
#define TT_428 AT(u8"隐藏窗体", u8"Hide Window", u8"ウィンドウを隠す")
#define TT_429 AT(u8"显示模型", u8"Show Model", u8"モデルを表示")
#define TT_430 AT(u8"隐藏模型", u8"Hide Model", u8"モデルを隠す")
#define TT_431 AT(u8"Windows 的窗体关闭",u8"Windows's close",u8"Windowsのウィンドウが閉じる")
#define TT_432 AT(u8"关闭时退出",u8"Exit When Closed",u8"閉じるときに終了する")
#define TT_433 AT(u8"关闭时缩放",u8"Zoom When Closed",u8"閉じるときに最小化する")
#define TT_434 AT(u8"Windows 的窗体透明", u8"Windows's alpha", u8"Windowsのウィンドウ透明度")

